# Generated by Django 5.2.14 on 2026-05-22 13:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccelerometerMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('accX', models.FloatField()),
                ('accY', models.FloatField()),
                ('accZ', models.FloatField()),
                ('angleX', models.FloatField()),
                ('angleY', models.FloatField()),
                ('angleZ', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AirQualityMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('aqi', models.IntegerField()),
                ('tvoc', models.IntegerField()),
                ('eco2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AtmosphericMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GNSSMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('altitude', models.FloatField(null=True)),
                ('satellites', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('q1', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q2', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q3', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q4', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q5', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q6', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q7', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q8', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q9', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q10', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('gnss_snapshot', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_cube.gnssmeasurement')),
            ],
        ),
        migrations.CreateModel(
            name='RelativeImportanceSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('q1', models.FloatField(default=0.5)),
                ('q2', models.FloatField(default=0.5)),
                ('q3', models.FloatField(default=0.5)),
                ('q4', models.FloatField(default=0.5)),
                ('q5', models.FloatField(default=0.5)),
                ('q6', models.FloatField(default=0.5)),
                ('q7', models.FloatField(default=0.5)),
                ('q8', models.FloatField(default=0.5)),
                ('q9', models.FloatField(default=0.5)),
                ('q10', models.FloatField(default=0.5)),
                ('gnss_snapshot', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_cube.gnssmeasurement')),
            ],
        ),
    ]
