# Generated by Django 5.2.14 on 2026-05-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_cube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoiseMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('noise_db', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ParticulateMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pm1', models.IntegerField(default=0)),
                ('pm25', models.IntegerField(default=0)),
                ('pm10', models.IntegerField(default=0)),
            ],
        ),
    ]
